-- =========================================================
-- Create schema
-- =========================================================
CREATE SCHEMA IF NOT EXISTS uni;

-- =========================================================
-- Professor
-- =========================================================
CREATE TABLE uni.professor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    officeNumber VARCHAR(50)
);

-- =========================================================
-- Student
-- =========================================================
CREATE TABLE uni.student (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    age INTEGER CHECK (age > 0)
);

-- =========================================================
-- Course
-- =========================================================
CREATE TABLE uni.course (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    forDegree VARCHAR(50) NOT NULL
);

-- =========================================================
-- Professor ↔ Course Assignment
-- =========================================================
CREATE TABLE uni.professor_course_assignment (
    professorId INTEGER NOT NULL,
    courseId INTEGER NOT NULL,
    PRIMARY KEY (professorId, courseId),
    CONSTRAINT fk_professor
        FOREIGN KEY (professorId)
        REFERENCES uni.professor(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_course_professor
        FOREIGN KEY (courseId)
        REFERENCES uni.course(id)
        ON DELETE CASCADE
);

-- =========================================================
-- Student ↔ Course Assignment
-- =========================================================
CREATE TABLE uni.student_course_assignment (
    studentId INTEGER NOT NULL,
    courseId INTEGER NOT NULL,
    PRIMARY KEY (studentId, courseId),
    CONSTRAINT fk_student
        FOREIGN KEY (studentId)
        REFERENCES uni.student(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_course_student
        FOREIGN KEY (courseId)
        REFERENCES uni.course(id)
        ON DELETE CASCADE
);
